### ISSUE TITLE
mobilesam与BM1684X

### ISSUE THREAD

**Issue by zouyubin** [ZillaRU/AnnoSeg#1]
![81E425F5-EC0C-48EB-B762-950BF72CD37A](https://github.com/ZillaRU/AnnoSeg/assets/70570092/b75a5f5d-4703-4f2e-8a33-f0145ce54b15)

你好，你这个项目使用的是mobilesam tinyViT(5.78M)吗？我看到你们已经转了模型，运行在BM1684X上了，能方便提供一下转模型的指引吗？我想把mobilesam ViT-H(632M)转模型，让vit-h跑在BM1684X上，谢谢！

**Comment by ZillaRU** [comment]
对的。这个仓库的image encoder使用的是tinyVIT。更大的sam模型导出可以参考这个https://github.com/vietanhdev/samexporter 来转onnx，然后再用tpumlir导bmodel。
