### ISSUE TITLE
mobilesam_encoder.onnx转bmodel错误

### ISSUE THREAD

**Issue by Jinfeng50** [ZillaRU/AnnoSeg#3]
请问我在尝试复现时，mask_decoder和sam_vit_h都成功转出了bmodel，但在mobilesam的encoder转换时报了如下错误：
`Traceback (most recent call last):
  File "/workspace/python/tools/model_deploy.py", line 344, in <module>
    tool.build_model()
  File "/workspace/python/tools/model_deploy.py", line 235, in build_model
    mlir_to_model(self.tpu_mlir, self.model, self.final_mlir, self.dynamic,
  File "/workspace/python/utils/mlir_shell.py", line 172, in mlir_to_model
    _os_system(cmd)
  File "/workspace/python/utils/mlir_shell.py", line 50, in _os_system
raise RuntimeError("[!Error]: {}".format(cmd_str))
RuntimeError: [!Error]: tpuc-opt mobile_sam_bm1684x_f16_final.mlir --codegen="model_file=mobile_sam_fp16.bmodel embed_debug_info=false model_version=latest" -o /dev/null `

请问这是为什么，我是尝试转BM1864X的fp32的模型，所使用的命令如下：
onnx转mlir：
model_transform.py --model_name mobile_sam --model_def mobile_sam.onnx --input_shapes [1024,1024,3] --mlir mobile_sam.mlir 
mlir转bmodel：（错误发生在这一步）
model_deploy.py --mlir mobile_sam.mlir --quantize F16 --chip bm1684x --model mobile_sam_fp16.bmodel

希望得到解答，感谢！

**Comment by ZillaRU** [comment]
您用的tpumlir是什么版本的？我当时似乎没遇到这个问题。

**Comment by Jinfeng50** [comment]
谢谢解答！这个问题我已经解决！
但是我想请教，例程中使用的decoder.bmodel是使用原生sam的pth权重转出来的吗，还是需要对生成onnx的程序做一定修改呢？

**Comment by ZillaRU** [comment]
这个记不清了。
mobilesam是通过蒸馏将原生sam的 VIT-H 特征蒸馏到一个 VIT-Tiny 上，然后再单独优化 mask decoder（mask decoder结构不变，finetune不是必须的）。
我导出的时候encoder部分参考的sam exporter导出的。后面decoder是自己导的，可能是mobilesam微调过的吧。
