### ISSUE TITLE
网络摄像头？

### ISSUE THREAD

**Issue by Jinfeng50** [ZillaRU/AnnoSeg#4]
请问程序中似乎没有关于网络摄像头调用的部分，如果我要处理实时画面，是否需要自己修改程序呢？我需要怎么做？

**Comment by ZillaRU** [comment]
需要自己修改。网络摄像头调用这个gpt一下就可以了。
另外要处理实时画面的话，当前版本的FPS不够呢。可以考虑：
1. 用cpp重写pipeline，比如https://github.com/YavorGIvanov/sam.cpp
2. 检测和分割的预处理也放在tpu上做。
3. 采用流水线增加并行。（当前检测模型和分割模型是串行的，这两个应该可以并行；预处理和之后的模型推理可能也能并行。）

**Comment by Jinfeng50** [comment]
> 需要自己修改。网络摄像头调用这个gpt一下就可以了。 另外要处理实时画面的话，当前版本的FPS不够呢。可以考虑：
> 
> 1. 用cpp重写pipeline，比如https://github.com/YavorGIvanov/sam.cpp
> 2. 检测和分割的预处理也放在tpu上做。
> 3. 采用流水线增加并行。（当前检测模型和分割模型是串行的，这两个应该可以并行；预处理和之后的模型推理可能也能并行。）

请问重写pipline具体是如何实现，这一部分并不是很了解

**Comment by ZillaRU** [comment]
要cpp重写的话就是参考[sam.cpp](https://github.com/YavorGIvanov/sam.cpp)把pipeline用cpp重写，再参考bmruntime[文档](https://doc.sophgo.com/docs/3.0.0/docs_latest_release/nntc/html/usage/runtime.html)写模型加载输入输出销毁的部分。
这个仓库里用的sail这个包其实就是在bmruntime上的封装。

**Comment by Jinfeng50** [comment]
> 要cpp重写的话就是参考[sam.cpp](https://github.com/YavorGIvanov/sam.cpp)把pipeline用cpp重写，再参考bmruntime[文档](https://doc.sophgo.com/docs/3.0.0/docs_latest_release/nntc/html/usage/runtime.html)写模型加载输入输出销毁的部分。 这个仓库里用的sail这个包其实就是在bmruntime上的封装。

谢谢！按我的理解，使用cpp重写了pipeline之后，是不是意味着可以更方便的调用流水线工作，那这时候我是否要把程序中的app.py也用cpp改写呢

**Comment by ZillaRU** [comment]
是的，更高效而且方便写流水线。
app.py还是python就可以。可以把Cpp写的sam这部分作为一个算法module，允许python调用。这部分可以参考一下 https://github.com/k2-fsa/sherpa-onnx 这个项目，用cpp实现了语音识别的库，允许c、python、java、go等等各种语言调用（我很少写cpp，最近在学习这个项目= =

**Comment by Jinfeng50** [comment]
> 是的，更高效而且方便写流水线。 app.py还是python就可以。可以把Cpp写的sam这部分作为一个算法module，允许python调用。这部分可以参考一下 https://github.com/k2-fsa/sherpa-onnx 这个项目，用cpp实现了语音识别的库，允许c、python、java、go等等各种语言调用（我很少写cpp，最近在学习这个项目= =

谢谢！我也是很少写cpp，所以并不是很懂，我后续会努力尝试一下，非常感谢！

**Comment by Jinfeng50** [comment]
你好！其实我一开始的想法是通过拉去摄像头的视频流，然后在后台做与本地视频一样的帧处理，然后再返回成视频文件自动播放，在gradio里显示，但从目前的运行来看将会有很大的延迟，请问这个方法是否就不可行呢？必须要使用cpp来加速

**Comment by ZillaRU** [comment]
延迟会很大。可能处理时间是视频时长的好几倍。

**Comment by Jinfeng50** [comment]
> 延迟会很大。可能处理时间是视频时长的好几倍。

所以我一开始希望启用python的进程池来处理，感觉是否也是一种方法？

**Comment by ZillaRU** [comment]
可以试试。
